name: Python CI 
on:
  - push 
jobs: 
  test: 
    # add environment
    environment: 
      name: dev 
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v2
      with:
          python-version: '3.6'
    

  build:
    runs-on: ubuntu-latest
    needs: 
    - test
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v2
      with:
          python-version: '3.6'
    - run: pip3 install -r requirements.txt
    - run: python3 HelloWorld.py
